---
title: "Essay_2_Advanced_903"
output: html_document
---
#Setting up environment
```{r, echo=FALSE}
##Loading packages
library(foreign)
library(haven)
library(tidyverse)
library(cluster)  
library(factoextra)
library(corrplot)
library(xtable)
```
## Loading Data
```{r}
rm(list = ls())
WVS <- haven::read_sav('/Users/lukas/OneDrive - University of Warwick/Term2/Advanced Quanti/Essay_2_Advanced/EVS_WVS_Joint_v1.1.0 SPSS.sav')

#Selecting Columns on Norms and Ethics
WVS_limited <- WVS %>% 
  select(cntry_AN, 172:184 )
names(WVS_limited)

#Renaming all relevant variables
WVS_limited['Govenment_benefits'] <- WVS_limited$F114A
WVS_limited['Public_transport'] <- WVS_limited$F115
WVS_limited['Cheating_taxes'] <- WVS_limited$F116
WVS_limited['Accepting_bribe'] <- WVS_limited$F117
WVS_limited['Homosexuality'] <- WVS_limited$F118
WVS_limited['Prostitution'] <- WVS_limited$F119
WVS_limited['Abortion'] <- WVS_limited$F120
WVS_limited['Divorce'] <- WVS_limited$F121
WVS_limited['Euthanasia'] <- WVS_limited$F122
WVS_limited['Suicide'] <- WVS_limited$F123
WVS_limited['Casual_Sex'] <- WVS_limited$F132
WVS_limited['political_violence'] <- WVS_limited$E290
WVS_limited['Death_penalty'] <- WVS_limited$F144_02

WVS_final <- WVS_limited %>% 
  select(1, 15:27) %>% 
  drop_na()
names_data <- c(Govenment_benefits = 'Claiming Benefits',
                Public_transport = 'Fare Evasion', 
                Cheating_taxes = "Tax Fraud", 
                Accepting_bribe = "Bribery",
                Homosexuality = "Homosexuality", 
                Prostitution = "Prostitution",
                Abortion =  "Abortion", 
                Divorce = "Divorce", 
                Euthanasia = "Euthanasia", 
                Suicide = "Suicide", 
                Casual_Sex = "Casual Sex", 
                political_violence = "Political Violence", 
                Death_penalty = "Death Penalty" )
names_character <- c('Claiming Benefits',
                'Fare Evasion', 
                'Tax Fraud', 
                "Bribery",
                 "Homosexuality", 
                 "Prostitution",
                 "Abortion", 
                 "Divorce", 
                 "Euthanasia", 
                 "Suicide", 
                "Casual Sex", 
                 "Political Violence", 
                 "Death Penalty" )
```
```{r}
#Checking Count of Variables

WVS_final %>% 
  drop_na() %>% 
  group_by(cntry_AN) %>% 
  count() %>% 
  .[order(.$n),]
```
# Descriptive Statistics
```{r}
#Plot: Distribution of Norms across all Countries
WVS_final %>% 
  group_by(cntry_AN) %>% 
  summarise_at(.vars = names(.)[2:14],
               .funs = c(mean="mean")) %>% 
  gather(Features, value, 2:14)  %>%
  ggplot(aes(x=value)) +
  geom_density(fill="orange3", colour="black") +
  facet_wrap(~Features,ncol = 5, scales = "fixed", labeller =    as_labeller(names_data, default = label_wrap_gen(12))) +
  labs(x="Level of Approval", y="Density") +
  #ggtitle('Distribution of Norms across all Countries')+
  theme(plot.title = element_text(hjust = 0.5, size = 10, face = 'bold')) +
         theme(strip.text.x = element_text(size = 5, colour = "black", margin  = margin( b = 0.1, t = 0.1)),
              axis.text.x = element_text(size = 5, ),
              axis.text.y = element_text(size = 5),
              axis.title = element_text( size = 7, face = "bold"))

#ggsave("Pictures/histogramm.png", plot = last_plot())
```
```{r}
#Aggregating Data to country level
WVS_final %>% 
  group_by(cntry_AN) %>% 
  summarise(across(everything(), mean)) -> WVS_World
```

```{r}
#Calculating Mean Values
WVS_World %>% 
  summarise_at(.vars = names(.)[2:14],
               .funs = c(mean="mean")) %>% 
  t()
```

```{r}
### Plot: Correlations between variables
WVS_World %>% 
select(2:14) %>% 
  scale() %>% 
cor(., use="pairwise.complete.obs",method="spearman") -> cor
colnames(cor) <- names_data
rownames(cor) <- names_data
par(xpd=TRUE)
cor %>% 
round(2) %>% 
corrplot(.,type="lower",diag=F, order = 'hclust',tl.col = "black", tl.cex = 0.5, insig = "pch", addrect = 3, mar = c(0,0,2,0) )
```
#Analysis
## PCA Analysis
```{r}
#Running PCA on whole Dataset (Number of Countries = 42)

res.pca_world <- WVS_World %>% 
  column_to_rownames('cntry_AN') %>% 
  as.data.frame() %>% 
  stats::prcomp(., scale = TRUE)

res.pca_world$x
```

```{r}
## Plotting Eigenvalues to find the right amount of components
fviz_eig(res.pca_world, main = 'Plotting Eigenvalues of Principal Components')
ggsave('Pictures/components_world.png', plot = last_plot())

## Plotting Variables and their impact on components 1 and 2
## I labeled the components to get a better feeling of their meaning
fviz_pca_biplot(res.pca_world,
              geom = c("point", "text"),
              col.var = "contrib", # Color by contributions to the PC
              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
              repel = T,     # Avoid text overlapping
              labelsize = 2,
              legend.title = "Weight") +
              labs(title ="Variable Loadings for PC1 and PC2", x = "PC1: Secular Behavior ", y = "PC2: Antisocial Behavior ") +
             theme(plot.title = element_text(hjust = 0.5, size = 11, face = 'bold'), axis.title = element_text(size = 8))

# ## Plotting both variables and individual data points
# fviz_pca_biplot(res.pca_world,
#              col.var = "contrib", # Color by contributions to the PC
#              gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
#              repel = T,     # Avoid text overlapping
#              labelsize = 2) +
#             labs(title ="PCs for Countries", x = "Dimension: Secular Behavior ", y = "Dimension: Antisocial Behavior ") + theme(plot.title = element_text(hjust = 0.5, size = 11, face = 'bold')) + #Naming PCs
#     xlim(-10, 10)+
#   ylim(-7,7)
# 
# ggsave("Pictures/Biplot_World.png", plot = last_plot())


## Plotting Correlation of each variable with each components
var <- get_pca_var(res.pca_world)
var2 <- var$cor[,1:7]
rownames(var2) <- names_character
corrplot(t(var2), method = "color", addCoef.col = "white", number.cex = .5, is.corr = FALSE, tl.col = "black", tl.cex = 0.5, insig = "pch", addrect = 3) 
#ggsave("Pictures/correlation_PCA_world.png", plot = last_plot())

```
##Clustering - Kmeans
```{r}
#https://www.r-bloggers.com/2017/02/finding-optimal-number-of-clusters/

#Preparing Data
positions <- res.pca_world$x[,1:3] %>% 
  scale()

#Finding the right amount of clusters
set.seed(123)
k.max <- 10
wss <- sapply(1:k.max, 
              function(k){kmeans(positions, k, nstart=25 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

# => Elbow method says that 4 clusters are good

nb_keans <- NbClust(positions, diss=NULL, distance = "euclidean", 
              min.nc=2, max.nc=5, method = "kmeans", 
              index = "all", alphaBeale = 0.1)
hist(nb$Best.nc[1,], breaks = max(na.omit(nb$Best.nc[1,])))

# => NbClust package suggests 4 as well

#Plotting Clusters
class(positions)
km.res <- kmeans(positions, 4, nstart = 25)
print(km.res)
fviz_cluster(km.res, positions, stand = F, repel = T)
ggsave('tt.png', plot = last_plot())
table(km.res$cluster)
print(xtable(km.res$centers, type = "latex"))
clusters <- as.data.frame(km.res$cluster)

clusters %>% arrange((km.res$cluster)) -> Ordered_df

print(xtable(Ordered_df, type = "latex"))
# Saving
```
# Appendices
## Citations
```{r}
#citations 
citation("tidyverse")
citation("factoextra")
citation("stats")
citation("NbClust")
```
